In [4]:
import pandas as pd

india_weather =pd.DataFrame({
    "city" : ["mumbai","delhi","banglore"],
    "temperature" : [32,45,30],
    "humidity" : [80,60,78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [5]:
usa_weather =pd.DataFrame({
    "city" : ["NewYork","chicago","orlando"],
    "temperature" : [21,14,35],
    "humidity" : [68,65,75]
})
usa_weather

      city  temperature  humidity
0  NewYork           21        68
1  chicago           14        65
2  orlando           35        75

In [6]:
pd.concat((india_weather,usa_weather))

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0   NewYork           21        68
1   chicago           14        65
2   orlando           35        75

In [7]:
pd.concat((india_weather,usa_weather), ignore_index=True)

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3   NewYork           21        68
4   chicago           14        65
5   orlando           35        75

In [11]:
df = pd.concat((india_weather,usa_weather), keys=["india" , "usa"])
df

             city  temperature  humidity
india 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
usa   0   NewYork           21        68
      1   chicago           14        65
      2   orlando           35        75

In [12]:
df.loc["india"]

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [13]:
df.loc["usa"]

      city  temperature  humidity
0  NewYork           21        68
1  chicago           14        65
2  orlando           35        75

In [19]:
temperature_df = pd.DataFrame({
    "city" : ["NewYork","chicago","orlando"],
    "temperature" : [21,14,35]
}, index=[0,1,2])
temperature_df

      city  temperature
0  NewYork           21
1  chicago           14
2  orlando           35

In [21]:
windspeed_df = pd.DataFrame({
    "city" : ["orlando","NewYork"],
    "windspeed" : [7,12]
}, index=[2,0])
windspeed_df

      city  windspeed
2  orlando          7
0  NewYork         12

In [22]:
df = pd.concat([temperature_df ,windspeed_df], axis=1)
df

      city  temperature     city  windspeed
0  NewYork           21  NewYork       12.0
1  chicago           14      NaN        NaN
2  orlando           35  orlando        7.0

In [23]:
temperature_df

      city  temperature
0  NewYork           21
1  chicago           14
2  orlando           35

In [26]:
s = pd.Series(["humid","dry","rain"], name="event")
s

0    humid
1      dry
2     rain
Name: event, dtype: object

In [27]:
df=pd.concat([temperature_df, s], axis=1)
df

      city  temperature  event
0  NewYork           21  humid
1  chicago           14    dry
2  orlando           35   rain