In [1]:
import pandas as pd
df = pd.read_csv("../Datasets/aapl_no_dates.csv")
df.head()

     Open    High     Low   Close    Volume
0  153.17  153.33  152.22  153.18  16404088
1  153.58  155.45  152.89  155.45  27770715
2  154.34  154.45  153.46  153.93  25331662
3  153.90  155.81  153.78  154.45  26624926
4  155.02  155.98  154.48  155.37  21069647

In [7]:
pd.date_range(start="7/1/2017",end="7/21/2017",freq='B')

DatetimeIndex(['2017-07-03', '2017-07-04', '2017-07-05', '2017-07-06',
               '2017-07-07', '2017-07-10', '2017-07-11', '2017-07-12',
               '2017-07-13', '2017-07-14', '2017-07-17', '2017-07-18',
               '2017-07-19', '2017-07-20', '2017-07-21'],
              dtype='datetime64[ns]', freq='B')

In [8]:
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

In [16]:
us_cal = CustomBusinessDay(calendar=USFederalHolidayCalendar())

rng = pd.date_range(start="7/1/2017", periods=len(df), freq=us_cal)

df.set_index(rng, inplace=True)

In [17]:

df.head()

              Open    High     Low   Close    Volume
2017-07-03  153.17  153.33  152.22  153.18  16404088
2017-07-05  153.58  155.45  152.89  155.45  27770715
2017-07-06  154.34  154.45  153.46  153.93  25331662
2017-07-07  153.90  155.81  153.78  154.45  26624926
2017-07-10  155.02  155.98  154.48  155.37  21069647

In [23]:
from pandas.tseries.holiday import AbstractHolidayCalendar,nearest_workday,Holiday
class myBirthDayCalendar(AbstractHolidayCalendar):
    rules = [
        Holiday("Bona's birthday",month=4,day=26)
    ]
myc = CustomBusinessDay(calendar=myBirthDayCalendar())
myc

In [24]:
pd.date_range(start='4/1/2017',end='4/30/2017',freq=myc)

DatetimeIndex(['2017-04-03', '2017-04-04', '2017-04-05', '2017-04-06',
               '2017-04-07', '2017-04-10', '2017-04-11', '2017-04-12',
               '2017-04-13', '2017-04-14', '2017-04-17', '2017-04-18',
               '2017-04-19', '2017-04-20', '2017-04-21', '2017-04-24',
               '2017-04-25', '2017-04-27', '2017-04-28'],
              dtype='datetime64[ns]', freq='C')