In [2]:
import pandas as pd

df = pd.read_csv("house_prices.csv")
df

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,187526,3 BHK Ready to Occupy Flat for sale in Bollywo...,This magnificent 3 BHK Flat is available for s...,63 Lac,3225.0,zirakpur,NaN,Ready to Move,2 out of 4,New Property,...,East,Garden/Park,Bollywood Esencia,3,3,1 Covered,Freehold,1953 sqft,NaN,NaN
187527,187527,3 BHK Ready to Occupy Flat for sale in Sushma ...,Have a look at this immaculate 3 BHK flat for ...,55 Lac,3274.0,zirakpur,NaN,Ready to Move,4 out of 6,Resale,...,North - East,"Garden/Park, Main Road",Sushma Urban Views,3,NaN,1 Covered,NaN,1680 sqft,NaN,NaN
187528,187528,3 BHK Ready to Occupy Flat for sale in Bollywo...,"Gazipur, Zirakpur has an appealing 3 BHK flat ...",76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,1 out of 3,Resale,...,East,"Garden/Park, Main Road",Bollywood Esencia,3,2,"1 Covered,",Freehold,NaN,NaN,NaN
187529,187529,2 BHK Ready to Occupy Flat for sale in Friends...,Up for immediate sale is a 2 BHK apartment in ...,30 Lac,4231.0,zirakpur,NaN,Ready to Move,2 out of 2,Resale,...,NaN,Main Road,Friends Enclave,2,NaN,NaN,NaN,709 sqft,NaN,NaN
187530,187530,3 BHK Ready to Occupy Flat for sale in Affinit...,This exquisite 3 BHK Flat is offered for sale ...,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,5 out of 13,Resale,...,North - East,"Garden/Park, Pool",Affinity Greens,4,4,1 Covered,Freehold,1915 sqft,NaN,NaN

In [5]:
df.drop(columns=["Dimensions", "Plot Area"])

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,NaN,NaN,1,1,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,187526,3 BHK Ready to Occupy Flat for sale in Bollywo...,This magnificent 3 BHK Flat is available for s...,63 Lac,3225.0,zirakpur,NaN,Ready to Move,2 out of 4,New Property,Semi-Furnished,East,Garden/Park,Bollywood Esencia,3,3,1 Covered,Freehold,1953 sqft
187527,187527,3 BHK Ready to Occupy Flat for sale in Sushma ...,Have a look at this immaculate 3 BHK flat for ...,55 Lac,3274.0,zirakpur,NaN,Ready to Move,4 out of 6,Resale,Unfurnished,North - East,"Garden/Park, Main Road",Sushma Urban Views,3,NaN,1 Covered,NaN,1680 sqft
187528,187528,3 BHK Ready to Occupy Flat for sale in Bollywo...,"Gazipur, Zirakpur has an appealing 3 BHK flat ...",76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,1 out of 3,Resale,Furnished,East,"Garden/Park, Main Road",Bollywood Esencia,3,2,"1 Covered,",Freehold,NaN
187529,187529,2 BHK Ready to Occupy Flat for sale in Friends...,Up for immediate sale is a 2 BHK apartment in ...,30 Lac,4231.0,zirakpur,NaN,Ready to Move,2 out of 2,Resale,Semi-Furnished,NaN,Main Road,Friends Enclave,2,NaN,NaN,NaN,709 sqft
187530,187530,3 BHK Ready to Occupy Flat for sale in Affinit...,This exquisite 3 BHK Flat is offered for sale ...,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,5 out of 13,Resale,Semi-Furnished,North - East,"Garden/Park, Pool",Affinity Greens,4,4,1 Covered,Freehold,1915 sqft

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        184508 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  object
 6   Carpet Area        106858 non-null  object
 7   Status             186916 non-null  object
 8   Floor              180454 non-null  object
 9   Transaction        187448 non-null  object
 10  Furnishing         184634 non-null  object
 11  facing             117298 non-null  object
 12  overlooking        106095 non-null  object
 13  Society            77853 non-null   object
 14  Bathroom           186703 non-null  object
 15  Balcony            138596 non-null  object
 16  Car Parking        84174 non-null   object
 17  Ownership          122014 non-null  object
 18  Super Area         79846 non-null   object
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), object(17)
memory usage: 30.0+ MB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [10]:
df.drop(columns=['Society', 'Car Parking', 'Super Area'], inplace=True)

In [11]:
df.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Bathroom                828
Balcony               48935
Ownership             65517
Dimensions           187531
Plot Area            187531
dtype: int64

In [12]:
df.drop(columns=["Dimensions","Plot Area"], inplace=True)

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Bathroom,Balcony,Ownership
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,NaN,1,2,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,2,NaN,Freehold
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,2,NaN,Freehold
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,NaN,1,1,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",2,NaN,Co-operative Society
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,187526,3 BHK Ready to Occupy Flat for sale in Bollywo...,This magnificent 3 BHK Flat is available for s...,63 Lac,3225.0,zirakpur,NaN,Ready to Move,2 out of 4,New Property,Semi-Furnished,East,Garden/Park,3,3,Freehold
187527,187527,3 BHK Ready to Occupy Flat for sale in Sushma ...,Have a look at this immaculate 3 BHK flat for ...,55 Lac,3274.0,zirakpur,NaN,Ready to Move,4 out of 6,Resale,Unfurnished,North - East,"Garden/Park, Main Road",3,NaN,NaN
187528,187528,3 BHK Ready to Occupy Flat for sale in Bollywo...,"Gazipur, Zirakpur has an appealing 3 BHK flat ...",76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,1 out of 3,Resale,Furnished,East,"Garden/Park, Main Road",3,2,Freehold
187529,187529,2 BHK Ready to Occupy Flat for sale in Friends...,Up for immediate sale is a 2 BHK apartment in ...,30 Lac,4231.0,zirakpur,NaN,Ready to Move,2 out of 2,Resale,Semi-Furnished,NaN,Main Road,2,NaN,NaN
187530,187530,3 BHK Ready to Occupy Flat for sale in Affinit...,This exquisite 3 BHK Flat is offered for sale ...,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,5 out of 13,Resale,Semi-Furnished,North - East,"Garden/Park, Pool",4,4,Freehold

In [13]:
df.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Bathroom                828
Balcony               48935
Ownership             65517
Dimensions           187531
Plot Area            187531
dtype: int64

In [14]:
df.drop(columns=["Dimensions","Plot Area"], inplace=True)

In [15]:
df.isnull().sum()

Index                    0
Title                    0
Description           3023
Amount(in rupees)        0
Price (in rupees)    17665
location                 0
Carpet Area          80673
Status                 615
Floor                 7077
Transaction             83
Furnishing            2897
facing               70233
overlooking          81436
Bathroom               828
Balcony              48935
Ownership            65517
dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        184508 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  object
 6   Carpet Area        106858 non-null  object
 7   Status             186916 non-null  object
 8   Floor              180454 non-null  object
 9   Transaction        187448 non-null  object
 10  Furnishing         184634 non-null  object
 11  facing             117298 non-null  object
 12  overlooking        106095 non-null  object
 13  Bathroom           186703 non-null  object
 14  Balcony            138596 non-null  object
 15  Ownership          122014 non-null  object
dtypes: float64(1), int64(1), object(14)
memory usage: 22.9+ MB

In [17]:
df.drop(columns="Index", inplace=True)

In [18]:
for i in df.columns:
    print(i)
    print(df[i].value_counts())

Title
Title
2 BHK Ready to Occupy Flat for sale in Divyasree Elan Sarjapur Road                   2106
4 BHK Ready to Occupy Flat for sale in Hamdam Apartment Dwarka Sector 18              1647
2 BHK Ready to Occupy Flat for sale Nayabad                                           1295
3 BHK Ready to Occupy Flat for sale in Shree Vardhman Victoria Sector 70              1147
3 BHK Ready to Occupy Flat for sale Jagatpur                                           986
                                                                                      ...
3 BHK Ready to Occupy Flat for sale in Planner N Maker Homes Uttam Nagar West            1
3 BHK Ready to Occupy Flat for sale Rohini Sector 8                                      1
3 BHK Ready to Occupy Flat for sale in IFS Apartments Acharya Niketan, Mayur Vihar       1
2 BHK Ready to Occupy Flat for sale in Joshi Lane Karol Bagh                             1
2 BHK Ready to Occupy Flat for sale in Friends Enclave Kishanpura                        1
Name: count, Length: 32446, dtype: int64
Description
Description
Multistorey apartment is available for sale. It is a good location property. Please contact for more details.                                                                                                                                                                                                                                                                                                                                            2732
This gorgeous 4 BHK Flat is available for sale in Janakpuri Block C1, New Delhi. This flat is an attractive property for sale. This ready to move flat in Janakpuri Block C1 comes at an affordable price of INR 4.35 Cr. This flat is an ideal choice because it is an semi-furnished apartment with all basic amenities. Some neighbouring landmarks are its prime location park facing newly build floor in jankapuri c block.                         821
This gorgeous 1 BHK Flat is available for sale in Rohini, New Delhi. This flat all equipped with required facilities, is up for resale. This ready to move flat in Rohini can be availed at a reasonable price of INR 50 Lac. The flat is sold in unfurnished condition.                                                                                                                                                                                  821
One can find this stunning 1 BHK flat for sale in Uttam Nagar West, New Delhi. Your search ends here, because this flat for resale is among the best bargains in town. This ready to move flat in Uttam Nagar West can be taken at a very economical pricing of INR 18 Lac. The flat is available in furnished condition.                                                                                                                                 821
This exquisite 2 BHK Flat is offered for sale in Dwarka Mor, New Delhi. This flat for sale has a desirable location. This apartment ready to move in the Dwarka Mor is available for an attractive price of INR 23 Lac. The spacious apartment is furnished. The flat is easily approachable because it is near to dwarka mor metro station.                                                                                                              821
                                                                                                                                                                                                                                                                                                                                                                                                                                                         ...
This exquisite 3 BHK Flat is offered for sale in Rohini Sector 24, New Delhi. This is one of the best properties available for sale. This apartment ready to move in the Rohini Sector 24 is available for an attractive price of INR 85 Lac. The flat is available in semi-furnished condition. The property is constructed with proximity to major landmarks like prince public school.                                                                   1
Carefully laid out in the prime location of Sanjay Enclave in New Delhi, this spacious 2 BHK flat on sale is a meticulously planned project. This apartment for resale is a great choice. This ready to move flat located in Sanjay Enclave is available for purchase at a fair price of INR 32 Lac. The flat is unfurnished and makes for an ideal choice for any family. Prominent landmarks in and around this locality are near by rajapuri road.       1
This magnificent 2 BHK Flat is available for sale in Indraprastha Extension, New Delhi. It is in a prime location within the Amrapali Apartment. This is one of the best properties available for resale. This ready to move flat in Indraprastha Extension comes at an affordable price of INR 1 Cr. It is a semi-furnished apartment. The property is constructed with proximity to major landmarks like near balco market.                               1
This beautiful 3 BHK Flat is available for sale in Jasola Vihar, New Delhi. This apartment for resale is a great choice. This ready to move flat in Jasola Vihar is available for a reasonable price of INR 2.65 Cr. This flat is an ideal choice because it is an unfurnished apartment with all basic amenities. noida sarita vihar mohan estate nehru place apollo hospital are a few nearby landmarks.                                                  1
This exquisite 3 BHK Flat is offered for sale in Airport Road, Zirakpur. This flat is situated within the renown township of Affinity Greens. This flat for resale is a choice property. This ready to move flat in Airport Road comes at an affordable price of INR 1.18 Cr. The flat is semi-furnished and is suitable for any family size. this property is located on airport road, zirakpur are some major landmarks near the apartment.               1
Name: count, Length: 65634, dtype: int64
Amount(in rupees)
Amount(in rupees)
Call for Price    9684
85 Lac            5264
65 Lac            4229
60 Lac            3869
70 Lac            3801
                  ...
21.60 Cr             1
21.45 Cr             1
9.45 Cr              1
13.6 Lac             1
9.90 Cr              1
Name: count, Length: 1561, dtype: int64
Price (in rupees)
Price (in rupees)
4000.0     2463
5000.0     2286
10000.0    2273
3200.0     1479
18000.0    1420
           ...
8808.0        1
7864.0        1
10707.0       1
10680.0       1
2508.0        1
Name: count, Length: 10958, dtype: int64
location
location
new-delhi      27599
bangalore      24030
kolkata        22380
gurgaon        20070
ahmedabad      12750
               ...
nellore           30
solapur           30
madurai           30
palakkad          30
pondicherry       30
Name: count, Length: 81, dtype: int64
Carpet Area
Carpet Area
1000 sqft    5285
900 sqft     4649
1300 sqft    3457
1600 sqft    2752
600 sqft     2225
             ...
1867 sqft       1
2415 sqft       1
1712 sqft       1
2404 sqft       1
136 sqft        1
Name: count, Length: 2758, dtype: int64
Status
Status
Ready to Move    186916
Name: count, dtype: int64
Floor
Floor
2 out of 4      12433
1 out of 4      11985
3 out of 4       8792
1 out of 3       7093
4 out of 4       6253
                ...
30 out of 51        1
29 out of 33        1
19 out of 52        1
14 out of 42        1
7 out of 70         1
Name: count, Length: 947, dtype: int64
Transaction
Transaction
Resale          144172
New Property     42565
Other              709
Rent/Lease           2
Name: count, dtype: int64
Furnishing
Furnishing
Semi-Furnished    88318
Unfurnished       76154
Furnished         20162
Name: count, dtype: int64
facing
facing
East            54741
North - East    24220
North           16533
West             8574
South            4694
North - West     3843
South - East     2622
South -West      2071
Name: count, dtype: int64
overlooking
overlooking
Main Road                                      32193
Garden/Park, Main Road                         27238
Garden/Park                                    23077
Garden/Park, Pool, Main Road                   12413
Pool, Garden/Park, Main Road                    3615
Garden/Park, Pool                               2880
Main Road, Garden/Park, Pool                    1359
Pool, Main Road                                 1136
Pool                                            1012
Main Road, Garden/Park                           666
Pool, Garden/Park                                435
Garden/Park, Main Road, Pool                      39
Main Road, Pool                                   11
Main Road, Pool, Garden/Park                       8
Pool, Main Road, Garden/Park                       6
Main Road, Not Available                           4
Garden/Park, Pool, Main Road, Not Available        1
Garden/Park, Not Available                         1
Pool, Main Road, Not Available                     1
Name: count, dtype: int64
Bathroom
Bathroom
2       93007
3       55781
1       18654
4       15600
5        3343
6         209
> 10       35
7          35
10         14
8          14
9          11
Name: count, dtype: int64
Balcony
Balcony
2       51809
1       49219
3       27111
4        9420
5         841
6         132
> 10       22
7          14
10         13
8          13
9           2
Name: count, dtype: int64
Ownership
Ownership
Freehold                112229
Leasehold                 5285
Co-operative Society      3431
Power Of Attorney         1069
Name: count, dtype: int64

In [19]:
house_df = df.copy()

In [20]:
cols_to_fill_unknown = ['Description', 'facing', 'overlooking', 'Ownership']
house_df[cols_to_fill_unknown] = house_df[cols_to_fill_unknown].fillna('Unknown')

In [21]:
mean_price = house_df['Price (in rupees)'].mean()
house_df['Price (in rupees)'].fillna(mean_price, inplace=True)

C:\Users\hp naw\AppData\Local\Temp\ipykernel_14260\78256001.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  house_df['Price (in rupees)'].fillna(mean_price, inplace=True)

In [22]:
cols_to_fill_mode = ['Status', 'Transaction', 'Furnishing']
for col in cols_to_fill_mode:
    mode_val = house_df[col].mode().iloc[0]
    house_df[col].fillna(mode_val, inplace=True)

C:\Users\hp naw\AppData\Local\Temp\ipykernel_14260\1909544358.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  house_df[col].fillna(mode_val, inplace=True)

In [23]:
house_df['Bathroom'] = pd.to_numeric(house_df['Bathroom'], errors='coerce')
house_df['Balcony'] = pd.to_numeric(house_df['Balcony'], errors='coerce')

In [24]:
mean_bathroom = house_df['Bathroom'].mean()
mean_balcony = house_df['Balcony'].mean()
house_df['Bathroom'].fillna(mean_bathroom, inplace=True)
house_df['Balcony'].fillna(mean_balcony, inplace=True)

C:\Users\hp naw\AppData\Local\Temp\ipykernel_14260\2604373243.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  house_df['Bathroom'].fillna(mean_bathroom, inplace=True)
C:\Users\hp naw\AppData\Local\Temp\ipykernel_14260\2604373243.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  house_df['Balcony'].fillna(mean_balcony, inplace=True)

In [25]:
house_df.loc[house_df['Bathroom'] == '>10', 'Bathroom'] = 11
house_df['Bathroom'] = house_df['Bathroom'].astype(int)

In [26]:
house_df.loc[house_df['Balcony'] == '>10', 'Balcony'] = 11
house_df['Balcony'] = house_df['Balcony'].astype(int)

In [27]:
print(house_df.isnull().sum())

Title                    0
Description              0
Amount(in rupees)        0
Price (in rupees)        0
location                 0
Carpet Area          80673
Status                   0
Floor                 7077
Transaction              0
Furnishing               0
facing                   0
overlooking              0
Bathroom                 0
Balcony                  0
Ownership                0
dtype: int64

In [28]:
house_df.head()

,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Bathroom,Balcony,Ownership
0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,Unknown,Unknown,1,2,Unknown
1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,2,2,Freehold
2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,2,2,Freehold
3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,Unknown,Unknown,1,1,Unknown
4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",2,2,Co-operative Society

In [29]:
df[['Carpet Area','Floor']]

       Carpet Area         Floor
0         500 sqft  10 out of 11
1         473 sqft   3 out of 22
2         779 sqft  10 out of 29
3         530 sqft    1 out of 3
4         635 sqft  20 out of 42
...            ...           ...
187526         NaN    2 out of 4
187527         NaN    4 out of 6
187528   1250 sqft    1 out of 3
187529         NaN    2 out of 2
187530         NaN   5 out of 13

[187531 rows x 2 columns]

In [32]:
import numpy as np
def convert_to_sqft(area):
    try:
        if pd.notnull(area):
            if 'sqft' in area:
                area = float(area.replace(' sqft', ''))
            else:
                area = float(area.replace(' sqm', '')) * 10.7639  # Convert square meters to square feet
            return area
    except ValueError:
        return np.nan

house_df['Carpet Area'] = house_df['Carpet Area'].apply(convert_to_sqft)

In [33]:
mean_carpet_area = house_df['Carpet Area'].mean()
house_df['Carpet Area'].fillna(mean_carpet_area, inplace=True)

C:\Users\hp naw\AppData\Local\Temp\ipykernel_14260\4116551704.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  house_df['Carpet Area'].fillna(mean_carpet_area, inplace=True)

In [35]:
house_df['Carpet Area'] = house_df['Carpet Area'].astype(int).astype(str) + ' sqft'

In [36]:
mode_floor = house_df['Floor'].mode().iloc[0]
house_df['Floor'].fillna(mode_floor, inplace=True)

C:\Users\hp naw\AppData\Local\Temp\ipykernel_14260\445190710.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  house_df['Floor'].fillna(mode_floor, inplace=True)

In [37]:
print(house_df.isnull().sum())

Title                0
Description          0
Amount(in rupees)    0
Price (in rupees)    0
location             0
Carpet Area          0
Status               0
Floor                0
Transaction          0
Furnishing           0
facing               0
overlooking          0
Bathroom             0
Balcony              0
Ownership            0
dtype: int64

In [38]:
house_df

,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Bathroom,Balcony,Ownership
0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,Unknown,Unknown,1,2,Unknown
1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,2,2,Freehold
2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,2,2,Freehold
3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,Unknown,Unknown,1,1,Unknown
4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",2,2,Co-operative Society
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187526,3 BHK Ready to Occupy Flat for sale in Bollywo...,This magnificent 3 BHK Flat is available for s...,63 Lac,3225.000000,zirakpur,1267 sqft,Ready to Move,2 out of 4,New Property,Semi-Furnished,East,Garden/Park,3,3,Freehold
187527,3 BHK Ready to Occupy Flat for sale in Sushma ...,Have a look at this immaculate 3 BHK flat for ...,55 Lac,3274.000000,zirakpur,1267 sqft,Ready to Move,4 out of 6,Resale,Unfurnished,North - East,"Garden/Park, Main Road",3,2,Unknown
187528,3 BHK Ready to Occupy Flat for sale in Bollywo...,"Gazipur, Zirakpur has an appealing 3 BHK flat ...",76 Lac,4343.000000,zirakpur,1250 sqft,Ready to Move,1 out of 3,Resale,Furnished,East,"Garden/Park, Main Road",3,2,Freehold
187529,2 BHK Ready to Occupy Flat for sale in Friends...,Up for immediate sale is a 2 BHK apartment in ...,30 Lac,4231.000000,zirakpur,1267 sqft,Ready to Move,2 out of 2,Resale,Semi-Furnished,Unknown,Main Road,2,2,Unknown
187530,3 BHK Ready to Occupy Flat for sale in Affinit...,This exquisite 3 BHK Flat is offered for sale ...,1.18 Cr,6162.000000,zirakpur,1267 sqft,Ready to Move,5 out of 13,Resale,Semi-Furnished,North - East,"Garden/Park, Pool",4,4,Freehold

In [39]:
house_df.duplicated().sum()

np.int64(119348)

In [40]:
house_df.drop_duplicates(inplace=True)

In [41]:
house_df.shape

(68183, 15)

In [42]:
df = house_df.copy()

In [43]:
df.head()

,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Bathroom,Balcony,Ownership
0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.000000,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,Unknown,Unknown,1,2,Unknown
1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.000000,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,2,2,Freehold
2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.000000,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,2,2,Freehold
3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,7583.771885,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,Unknown,Unknown,1,1,Unknown
4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.000000,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",2,2,Co-operative Society

In [44]:
df[['Amount(in rupees)','Carpet Area']]

       Amount(in rupees) Carpet Area
0                42 Lac     500 sqft
1                98 Lac     473 sqft
2               1.40 Cr     779 sqft
3                25 Lac     530 sqft
4               1.60 Cr     635 sqft
...                  ...         ...
187526           63 Lac    1267 sqft
187527           55 Lac    1267 sqft
187528           76 Lac    1250 sqft
187529           30 Lac    1267 sqft
187530          1.18 Cr    1267 sqft

[68183 rows x 2 columns]

In [45]:
def convert_amount(amount):
    try:
        if 'Lac' in amount:
            amount = amount.replace('Lac', '').strip()
            return float(amount) * 100000  # Convert Lac to rupees (1 Lac = 100000 rupees)
        elif 'Cr' in amount:
            amount = amount.replace('Cr', '').strip()
            return float(amount) * 10000000  # Convert Cr to rupees (1 Cr = 10000000 rupees)
        else:
            return float(amount)
    except ValueError:
        return None

df['Amount(in rupees)'] = df['Amount(in rupees)'].apply(convert_amount)

In [46]:
def convert_carpet_area(area):
    try:
        if 'sqft' in area:
            area = area.replace('sqft', '').strip()
            return float(area)  # Convert to square feet
        elif 'sqm' in area:
            area = area.replace('sqm', '').strip()
            return float(area) * 10.7639  # Convert square meters to square feet (1 sqm = 10.7639 sqft)
        else:
            return None
    except ValueError:
        return None

df['Carpet Area'] = df['Carpet Area'].apply(convert_carpet_area)

In [47]:
df.rename(columns={'Amount(in rupees)': 'Amount in rupees', 'Carpet Area': 'Carpet Area in sqft'}, inplace=True)

In [48]:
df.head()

,Title,Description,Amount in rupees,Price (in rupees),location,Carpet Area in sqft,Status,Floor,Transaction,Furnishing,facing,overlooking,Bathroom,Balcony,Ownership
0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",4200000.0,6000.000000,thane,500.0,Ready to Move,10 out of 11,Resale,Unfurnished,Unknown,Unknown,1,2,Unknown
1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,9800000.0,13799.000000,thane,473.0,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,2,2,Freehold
2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,14000000.0,17500.000000,thane,779.0,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,2,2,Freehold
3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,2500000.0,7583.771885,thane,530.0,Ready to Move,1 out of 3,Resale,Unfurnished,Unknown,Unknown,1,1,Unknown
4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",16000000.0,18824.000000,thane,635.0,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",2,2,Co-operative Society

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 68183 entries, 0 to 187530
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Title                68183 non-null  object
 1   Description          68183 non-null  object
 2   Amount in rupees     65248 non-null  float64
 3   Price (in rupees)    68183 non-null  float64
 4   location             68183 non-null  object
 5   Carpet Area in sqft  68183 non-null  float64
 6   Status               68183 non-null  object
 7   Floor                68183 non-null  object
 8   Transaction          68183 non-null  object
 9   Furnishing           68183 non-null  object
 10  facing               68183 non-null  object
 11  overlooking          68183 non-null  object
 12  Bathroom             68183 non-null  int64
 13  Balcony              68183 non-null  int64
 14  Ownership            68183 non-null  object
dtypes: float64(3), int64(2), object(10)
memory usage: 8.3+ MB

In [50]:
df.describe()

,Amount in rupees,Price (in rupees),Carpet Area in sqft,Bathroom,Balcony
count,6.524800e+04,6.818300e+04,68183.000000,68183.000000,68183.000000
mean,1.067952e+07,6.873848e+03,1282.707874,2.404030,2.060352
std,6.292855e+07,4.258265e+04,3741.375174,0.877477,0.854484
min,1.000000e+05,0.000000e+00,1.000000,1.000000,1.000000
25%,4.100000e+06,3.957000e+03,1030.000000,2.000000,2.000000
50%,6.500000e+06,5.357000e+03,1267.000000,2.000000,2.000000
75%,1.090000e+07,7.583772e+03,1267.000000,3.000000,2.000000
max,1.400300e+10,6.700000e+06,709222.000000,10.000000,10.000000

In [51]:
df.head()

,Title,Description,Amount in rupees,Price (in rupees),location,Carpet Area in sqft,Status,Floor,Transaction,Furnishing,facing,overlooking,Bathroom,Balcony,Ownership
0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",4200000.0,6000.000000,thane,500.0,Ready to Move,10 out of 11,Resale,Unfurnished,Unknown,Unknown,1,2,Unknown
1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,9800000.0,13799.000000,thane,473.0,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,2,2,Freehold
2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,14000000.0,17500.000000,thane,779.0,Ready to Move,10 out of 29,Resale,Unfurnished,East,Garden/Park,2,2,Freehold
3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,2500000.0,7583.771885,thane,530.0,Ready to Move,1 out of 3,Resale,Unfurnished,Unknown,Unknown,1,1,Unknown
4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",16000000.0,18824.000000,thane,635.0,Ready to Move,20 out of 42,Resale,Unfurnished,West,"Garden/Park, Main Road",2,2,Co-operative Society

In [52]:
df.duplicated().sum()

np.int64(0)

In [53]:
df.dtypes

Title                   object
Description             object
Amount in rupees       float64
Price (in rupees)      float64
location                object
Carpet Area in sqft    float64
Status                  object
Floor                   object
Transaction             object
Furnishing              object
facing                  object
overlooking             object
Bathroom                 int64
Balcony                  int64
Ownership               object
dtype: object

In [54]:
df.to_csv("edited_form.csv")