In [2]:
import pandas as pd
df = pd.read_excel("stocks.xlsx")
df

,Unnamed: 0,Price,Unnamed: 2,Unnamed: 3,Price to earnings ratio (P/E),Unnamed: 5,Unnamed: 6
0,Company,Facebook,Google,Microsoft,Facebook,Google,Microsoft
1,2017-06-05 00:00:00,155,955,66,37.1,32,30.31
2,2017-06-06 00:00:00,150,987,69,36.98,31.3,30.56
3,2017-06-07 00:00:00,153,963,62,36.78,31.7,30.46
4,2017-06-08 00:00:00,155,1000,61,36.11,31.2,30.11
5,2017-06-09 00:00:00,156,1012,66,37.07,30,31

In [5]:
df_stacked=df.stack(level=0)

In [7]:
df_stacked.unstack()

,Unnamed: 0,Price,Unnamed: 2,Unnamed: 3,Price to earnings ratio (P/E),Unnamed: 5,Unnamed: 6
0,Company,Facebook,Google,Microsoft,Facebook,Google,Microsoft
1,2017-06-05 00:00:00,155,955,66,37.1,32,30.31
2,2017-06-06 00:00:00,150,987,69,36.98,31.3,30.56
3,2017-06-07 00:00:00,153,963,62,36.78,31.7,30.46
4,2017-06-08 00:00:00,155,1000,61,36.11,31.2,30.11
5,2017-06-09 00:00:00,156,1012,66,37.07,30,31

In [10]:
df1=pd.read_excel("stocks_3_levels.xlsx",header=[0,1,2])
df1

  Unnamed: 0_level_0 Price Ratios                   \
  Unnamed: 0_level_1        Price
             Company     Facebook Google Microsoft
0            Q1 2016          155    955        66
1            Q2 2016          150    987        69
2            Q3 2016          153    963        62
3            Q4 2016          155   1000        61
4            Q1 2017          156   1012        66

                                                 Income Statement         \
  Price to earnings ratio (P/E)                         Net Sales
                       Facebook Google Microsoft         Facebook Google
0                         37.10   32.0     30.31              2.6     20
1                         36.98   31.3     30.56              3.1     22
2                         36.78   31.7     30.46              4.3     24
3                         36.11   31.2     30.11              6.7     26
4                         37.07   30.0     31.00              8.1     31


            Net Profit
  Microsoft   Facebook Google Microsoft
0     18.70       0.80   5.43      4.56
1     21.30       0.97   5.89      5.10
2     21.45       1.20   6.10      5.43
3     21.88       1.67   6.50      5.89
4     22.34       2.03   6.40      6.09

In [11]:
df1.stack()

C:\Users\hp naw\AppData\Local\Temp\ipykernel_7116\3088406619.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df1.stack()

            Unnamed: 0_level_0 Price Ratios                                \
            Unnamed: 0_level_1        Price Price to earnings ratio (P/E)
0 Company              Q1 2016          NaN                           NaN
  Facebook                 NaN        155.0                         37.10
  Google                   NaN        955.0                         32.00
  Microsoft                NaN         66.0                         30.31
1 Company              Q2 2016          NaN                           NaN
  Facebook                 NaN        150.0                         36.98
  Google                   NaN        987.0                         31.30
  Microsoft                NaN         69.0                         30.56
2 Company              Q3 2016          NaN                           NaN
  Facebook                 NaN        153.0                         36.78
  Google                   NaN        963.0                         31.70
  Microsoft                NaN         62.0                         30.46
3 Company              Q4 2016          NaN                           NaN
  Facebook                 NaN        155.0                         36.11
  Google                   NaN       1000.0                         31.20
  Microsoft                NaN         61.0                         30.11
4 Company              Q1 2017          NaN                           NaN
  Facebook                 NaN        156.0                         37.07
  Google                   NaN       1012.0                         30.00
  Microsoft                NaN         66.0                         31.00

            Income Statement
                   Net Sales Net Profit
0 Company                NaN        NaN
  Facebook              2.60       0.80
  Google               20.00       5.43
  Microsoft            18.70       4.56
1 Company                NaN        NaN
  Facebook              3.10       0.97
  Google               22.00       5.89
  Microsoft            21.30       5.10
2 Company                NaN        NaN
  Facebook              4.30       1.20
  Google               24.00       6.10
  Microsoft            21.45       5.43
3 Company                NaN        NaN
  Facebook              6.70       1.67
  Google               26.00       6.50
  Microsoft            21.88       5.89
4 Company                NaN        NaN
  Facebook              8.10       2.03
  Google               31.00       6.40
  Microsoft            22.34       6.09

In [12]:
df1.stack(level=1)

C:\Users\hp naw\AppData\Local\Temp\ipykernel_7116\2663534920.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df1.stack(level=1)

                                Unnamed: 0_level_0 Price Ratios          \
                                           Company     Facebook  Google
0 Net Profit                                   NaN          NaN     NaN
  Net Sales                                    NaN          NaN     NaN
  Price                                        NaN       155.00   955.0
  Price to earnings ratio (P/E)                NaN        37.10    32.0
  Unnamed: 0_level_1                       Q1 2016          NaN     NaN
1 Net Profit                                   NaN          NaN     NaN
  Net Sales                                    NaN          NaN     NaN
  Price                                        NaN       150.00   987.0
  Price to earnings ratio (P/E)                NaN        36.98    31.3
  Unnamed: 0_level_1                       Q2 2016          NaN     NaN
2 Net Profit                                   NaN          NaN     NaN
  Net Sales                                    NaN          NaN     NaN
  Price                                        NaN       153.00   963.0
  Price to earnings ratio (P/E)                NaN        36.78    31.7
  Unnamed: 0_level_1                       Q3 2016          NaN     NaN
3 Net Profit                                   NaN          NaN     NaN
  Net Sales                                    NaN          NaN     NaN
  Price                                        NaN       155.00  1000.0
  Price to earnings ratio (P/E)                NaN        36.11    31.2
  Unnamed: 0_level_1                       Q4 2016          NaN     NaN
4 Net Profit                                   NaN          NaN     NaN
  Net Sales                                    NaN          NaN     NaN
  Price                                        NaN       156.00  1012.0
  Price to earnings ratio (P/E)                NaN        37.07    30.0
  Unnamed: 0_level_1                       Q1 2017          NaN     NaN

                                          Income Statement
                                Microsoft         Facebook Google Microsoft
0 Net Profit                          NaN             0.80   5.43      4.56
  Net Sales                           NaN             2.60  20.00     18.70
  Price                             66.00              NaN    NaN       NaN
  Price to earnings ratio (P/E)     30.31              NaN    NaN       NaN
  Unnamed: 0_level_1                  NaN              NaN    NaN       NaN
1 Net Profit                          NaN             0.97   5.89      5.10
  Net Sales                           NaN             3.10  22.00     21.30
  Price                             69.00              NaN    NaN       NaN
  Price to earnings ratio (P/E)     30.56              NaN    NaN       NaN
  Unnamed: 0_level_1                  NaN              NaN    NaN       NaN
2 Net Profit                          NaN             1.20   6.10      5.43
  Net Sales                           NaN             4.30  24.00     21.45
  Price                             62.00              NaN    NaN       NaN
  Price to earnings ratio (P/E)     30.46              NaN    NaN       NaN
  Unnamed: 0_level_1                  NaN              NaN    NaN       NaN
3 Net Profit                          NaN             1.67   6.50      5.89
  Net Sales                           NaN             6.70  26.00     21.88
  Price                             61.00              NaN    NaN       NaN
  Price to earnings ratio (P/E)     30.11              NaN    NaN       NaN
  Unnamed: 0_level_1                  NaN              NaN    NaN       NaN
4 Net Profit                          NaN             2.03   6.40      6.09
  Net Sales                           NaN             8.10  31.00     22.34
  Price                             66.00              NaN    NaN       NaN
  Price to earnings ratio (P/E)     31.00              NaN    NaN       NaN
  Unnamed: 0_level_1                  NaN              NaN    NaN       NaN