In [6]:
import pandas as pd

df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando","Baltimore"],
    "temperature": [21,14,35,32],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  Baltimore           32

In [7]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","DC"],
    "humidity": [65,68,75],
})
df2

       city  humidity
0   chicago        65
1  new york        68
2        DC        75

In [11]:
df3=pd.merge(df1,df2,on="city",how="right",indicator=True)
df3

       city  temperature  humidity      _merge
0   chicago         14.0        65        both
1  new york         21.0        68        both
2        DC          NaN        75  right_only

In [12]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [13]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [14]:
df3=pd.merge(df1,df2,on="city",how="outer")
df3

        city  temperature  humidity
0  baltimore         38.0       NaN
1    chicago         14.0      65.0
2   new york         21.0      68.0
3    orlando         35.0       NaN
4  san diego          NaN      71.0

In [15]:
df1 = pd.DataFrame({ 
    "city" : ["newyork", "chicago","orlando","baltimore"],
    "temperature" : [21,14,35,38],
    "humidity" : [65,68,71,75]
})
df1

        city  temperature  humidity
0    newyork           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [16]:
df2 = pd.DataFrame({
    "city" : ["chicago","newyork","san diago"],
    "temperature" : [21,14,35],
    "humidity" : [65,68,71]
})
df2

        city  temperature  humidity
0    chicago           21        65
1    newyork           14        68
2  san diago           35        71

In [19]:
df3 = pd.merge(df1,df2,on="city", suffixes=('_left','_right'))
df3

      city  temperature_left  humidity_left  temperature_right  humidity_right
0  newyork                21             65                 14              68
1  chicago                14             68                 21              65