In [1]:
import pandas as pd

In [7]:
df=pd.read_csv("weather_data.csv", parse_dates=["day"])
df.set_index('day',inplace=True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [8]:
new_df=df.fillna(0)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [9]:
new_df= df.fillna({
    'temperature' : 0,
    'windspeed' : 0,
    'event' : "no event" })
new_df

            temperature  windspeed     event
day
2017-01-01         32.0        6.0      Rain
2017-01-04          0.0        9.0     Sunny
2017-01-05         28.0        0.0      Snow
2017-01-06          0.0        7.0  no event
2017-01-07         32.0        0.0      Rain
2017-01-08          0.0        0.0     Sunny
2017-01-09          0.0        0.0  no event
2017-01-10         34.0        8.0    Cloudy
2017-01-11         40.0       12.0     Sunny

In [11]:
new_df=df.fillna(method="bfill")
new_df

C:\Users\hp naw\AppData\Local\Temp\ipykernel_30212\3832046755.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df=df.fillna(method="bfill")

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [14]:
new_df = df.interpolate(method="time")
new_df

C:\Users\hp naw\AppData\Local\Temp\ipykernel_30212\3296454784.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate(method="time")

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    29.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

In [18]:
new_df = df.dropna(thresh=2)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny