In [4]:
import pandas as pd
df = pd.read_excel("survey.xlsx")
df

      Name Nationality     Sex  Age Handedness
0    Kathy         USA  Female   23      Right
1    Linda         USA  Female   18      Right
2    Peter         USA    Male   19      Right
3     John         USA    Male   22       Left
4   Fatima   Bangadesh  Female   31       Left
5    Kadir   Bangadesh    Male   25       Left
6   Dhaval       India    Male   35       Left
7   Sudhir       India    Male   31       Left
8   Parvir       India    Male   37      Right
9      Yan       China  Female   52      Right
10    Juan       China  Female   58       Left
11   Liang       China    Male   43       Left

In [6]:
pd.crosstab(df.Nationality,df.Handedness)

Handedness   Left  Right
Nationality
Bangadesh       2      0
China           2      1
India           2      1
USA             1      3

In [7]:
pd.crosstab(df.Sex,df.Handedness)

Handedness  Left  Right
Sex
Female         2      3
Male           5      2

In [9]:
pd.crosstab(df.Age,df.Handedness,margins=True)

Handedness  Left  Right  All
Age
18             0      1    1
19             0      1    1
22             1      0    1
23             0      1    1
25             1      0    1
31             2      0    2
35             1      0    1
37             0      1    1
43             1      0    1
52             0      1    1
58             1      0    1
All            7      5   12